config/routes.rb
Rails.application.routes.draw do
  get 'registrations/new'

  root 'front_pages#home'
  get 'about', to: 'front_pages#about', as: :front_about
  get 'contact', to: 'front_pages#contact', as: :front_contact
  get 'terms', to: 'front_pages#terms', as: :front_terms
  get 'privacy', to: 'front_pages#privacy', as: :front_privacy

  get 'dashboard', to: 'dashboards#show', as: :dashboard

  get 'login', to: 'sessions#new', as: :login
  get 'register', to: 'registrations#new', as: :registration
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end
end

app/controllers/front_pages_controller.rb
class FrontPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def terms
  end

  def privacy
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    render :new, layout: 'empty'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new, layout: 'empty'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Floworx'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/front_pages_helper.rb
module FrontPagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/dashboards/show.html.erb
<h1>Landlord::Dashboard#show</h1>
<p>Find me in app/views/landlord/dashboard/show.html.erb</p>

app/views/front_pages/about.html.erb
<% provide(:title, 'About') %>
<h2>About</h2>
<p>Floworx is a platform to make Architecture projects easier</p>
<%= link_to 'Home', root_path %>
<%= link_to 'Contact', front_contact_path %>
<%= link_to 'Terms', front_terms_path %>
<%= link_to 'Privacy', front_privacy_path %>

app/views/front_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h2>Contact</h2>
<p>Contact Floworx at:</p>
<%= link_to 'Home', root_path %>
<%= link_to 'About', front_about_path %>
<%= link_to 'Terms', front_terms_path %>
<%= link_to 'Privacy', front_privacy_path %>

app/views/front_pages/home.html.erb
<h2>Home</h2>
<%= link_to 'About', front_about_path %>
<%= link_to 'Contact', front_contact_path %>
<%= link_to 'Terms', front_terms_path %>
<%= link_to 'Privacy', front_privacy_path %>
<%= link_to 'Login', login_path %>

app/views/front_pages/privacy.html.erb
<% provide(:title, 'Privacy') %>
<h2>Privacy</h2>
<%= link_to 'Home', root_path %>
<%= link_to 'About', front_about_path %>
<%= link_to 'Contact', front_contact_path %>
<%= link_to 'Terms', front_terms_path %>

app/views/front_pages/terms.html.erb
<% provide(:title, 'Terms') %>
<h2>Terms</h2>
<%= link_to 'Home', root_path %>
<%= link_to 'About', front_about_path %>
<%= link_to 'Contact', front_contact_path %>
<%= link_to 'Privacy', front_privacy_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>INSPINIA</title>

  <!-- Main css styles -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <!-- Main javascript files -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<div id="wrapper">
  <%= render 'layouts/application/navigation' %>

  <div id="page-wrapper" class="gray-bg">
    <%= render 'layouts/application/topnavbar' %>
    <%= yield %>
    <%= render 'layouts/application/footer' %>
  </div>
</div>
</body>
</html>

app/views/layouts/application/_footer.html.erb
<div class="footer">
    <div class="pull-right">
      <%= link_to 'Privacy', '#' %> - <%= link_to 'Terms', '#' %>
    </div>
    <div>
      &copy; Floworx <%= Time.now.year %>
    </div>
</div>

app/views/layouts/application/_navigation.html.erb
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <span>
                      <%= image_tag 'profile-placeholder.png', class: 'img-circle nav-profile' %>
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear">
                            <span class="block m-t-xs">
                                <strong class="font-bold">Example user</strong>
                            </span> <span class="text-muted text-xs block">Example menu <b class="caret"></b></span>
                        </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="#">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    FW
                </div>
            </li>
            <li class="<%= 'active' if current_page?('/') %>">
                <%= link_to "/" do %>
                <i class="fa fa-laptop"></i> <span class="nav-label">Main page</span>
                <% end %>
            </li>
            <li class="<%= 'active' if current_page?('/home/minor') %>">
                <%= link_to "/home/minor" do %>
                <i class="fa fa-desktop"></i> <span class="nav-label">Minor page</span>
                <% end %>
            </li>
        </ul>

    </div>
</nav>

app/views/layouts/application/_topnavbar.html.erb
<div class="row border-bottom">
    <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <a href="#">
                    <i class="fa fa-sign-out"></i> Log out
                </a>
            </li>
        </ul>
    </nav>
</div>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="gray-bg">
  <%= yield %>
</body>
</html>

app/views/layouts/front_pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Floworx</h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>